recipe: default.v1
language: en
pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_group: rasa_command_generation_model
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy

- name: EnterpriseSearchPolicy
  llm:
    model_group: openai_llm
  embeddings:
    model_group: openai_embeddings
  vector_store:
    type: "faiss"
    source: "./docs"

assistant_id: 20250211-210351-beige-compass


